server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: media-group # L'identité du groupe d'écoute
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  application:
    name: media-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/buy01_media_db?authSource=admin
  # Configuration pour limiter la taille des fichiers uploadés
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/