server:
  port: 8084

spring:
  application:
    name: media-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/buy01_media_db?authSource=admin
  # Configuration pour limiter la taille des fichiers upload√©s
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/